export type PaisAmerica = { nombre: string; lada: string };

// Todos los países del continente americano (nombre en español + lada
// telefónica), para el selector de país del formulario de alta.
export const PAISES_AMERICA: PaisAmerica[] = [
  { nombre: "Antigua y Barbuda", lada: "+1" },
  { nombre: "Argentina", lada: "+54" },
  { nombre: "Bahamas", lada: "+1" },
  { nombre: "Barbados", lada: "+1" },
  { nombre: "Belice", lada: "+501" },
  { nombre: "Bolivia", lada: "+591" },
  { nombre: "Brasil", lada: "+55" },
  { nombre: "Canadá", lada: "+1" },
  { nombre: "Chile", lada: "+56" },
  { nombre: "Colombia", lada: "+57" },
  { nombre: "Costa Rica", lada: "+506" },
  { nombre: "Cuba", lada: "+53" },
  { nombre: "Dominica", lada: "+1" },
  { nombre: "Ecuador", lada: "+593" },
  { nombre: "El Salvador", lada: "+503" },
  { nombre: "Estados Unidos", lada: "+1" },
  { nombre: "Granada", lada: "+1" },
  { nombre: "Guatemala", lada: "+502" },
  { nombre: "Guyana", lada: "+592" },
  { nombre: "Haití", lada: "+509" },
  { nombre: "Honduras", lada: "+504" },
  { nombre: "Jamaica", lada: "+1" },
  { nombre: "México", lada: "+52" },
  { nombre: "Nicaragua", lada: "+505" },
  { nombre: "Panamá", lada: "+507" },
  { nombre: "Paraguay", lada: "+595" },
  { nombre: "Perú", lada: "+51" },
  { nombre: "Puerto Rico", lada: "+1" },
  { nombre: "República Dominicana", lada: "+1" },
  { nombre: "San Cristóbal y Nieves", lada: "+1" },
  { nombre: "San Vicente y las Granadinas", lada: "+1" },
  { nombre: "Santa Lucía", lada: "+1" },
  { nombre: "Surinam", lada: "+597" },
  { nombre: "Trinidad y Tobago", lada: "+1" },
  { nombre: "Uruguay", lada: "+598" },
  { nombre: "Venezuela", lada: "+58" },
];
